### ISSUE TITLE
Update to "The OpenConnect VPN Protocol Version 1.1 (draft-mavrogiannopoulos-openconnect-02)"

### ISSUE THREAD

**Issue by liuqun** [openconnect/protocol#2]
xml:
- https://tools.ietf.org/id/draft-mavrogiannopoulos-openconnect-02.xml

html:
- https://tools.ietf.org/id/draft-mavrogiannopoulos-openconnect-02.html 
The OpenConnect VPN Protocol Version 1.1
(draft-mavrogiannopoulos-openconnect-02)

Network Working Group | N. Mavrogiannopoulos
-- | --
Internet-Draft | Red Hat
Intended status: Informational | October 14, 2018
Expires: April 17, 2019

**Comment by nmav** [comment]
Hmm, indeed the xml was an older version. pushed the latest.
